server {
    server_name mail.miruum.id;
    location / { return 302 https://email.miruum.id/; }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mail.miruum.id/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mail.miruum.id/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = mail.miruum.id) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name mail.miruum.id;
    return 404; # managed by Certbot


}